plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nv.navigation'
    compileSdk 34

    defaultConfig {
        applicationId 'com.nv.navigation'
        minSdk 29
        targetSdk 34
        versionCode 51
        versionName '0.5.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
